---
title: "What is the next step?"
teaching: 10
exercises: 0
---


:::: questions

- "What do I do now?"
- "What is the next step?"

::::

:::: objectives

- "Present suggestions for further reading,"
- "Tips on problems to work on to practice,"

::::

## Where to learn more?

We have other courses in R - and other stuff. 

In our [calender](https://kubkalender.kb.dk/calendar/datalab?cid=6416&t=d&d=0000-00-00&cal=6416&inc=0), 
you will find all our activities, courses, seminars, datasprints etc.

There is an abundance of online courses in R, and a lot of other subjects.

Some of our favorites include: 

* [edx](https://www.edx.org/)

* [datacamp](https://www.datacamp.com/)

* [cognitive class](https://cognitiveclass.ai/)

A lot of online books also exists:

* [R for Data Science](https://r4ds.hadley.nz/). Absolutely brilliant!

* [Outstanding User Interfaces with Shiny](https://unleash-shiny.rinterface.com/)

## Where to find something to practice on?

You will only get proficient in R by practicing. If you already have your 
own data, and something you want to do with it, great! Go ahead.

But if you would like to find some data to play around with, here are some 
suggestions:

* [Kaggle](https://www.kaggle.com/) is an online machinelearning competition site. Doing machinelearning might be a bit premature for you, but they provides acccess to a _lot_ of interesting datasets.
* The [KUB Datalab website](https://kub.kb.dk/datalab/opendata) has a section on Open Data Sources.
* [Tidy Tuesday](https://github.com/rfordatascience/tidytuesday/blob/master/README.md) is an online event, where R enthusiasts every tuesday hack away on a common dataset. It's a great way to both discover new and interesting datasets, _and_ find inspiration for what to do with them.

If you want to dive into programming with R, rather than "just" data analysis, we
recommend [Project Euler](https://projecteuler.net/), witch is a collection of numerical
problems.

## But what should I do with that data?

Sometimes the most challenging thing is actually getting an idea for doing something.

[Fundamentals of Data Visualization](https://clauswilke.com/dataviz/) by Claus O. Wilke is a great 
book about visualizing data. No code unfortunately.

The [R Graph Gallery](https://r-graph-gallery.com/) provides both inspiration for 
visualizations and also the code! 

[R Screencasts](https://www.rscreencasts.com/) - what it says on the tin. Live data analysis, recorded.



## Contact us!

The whole reason for the existence of KUB Datalab is to help and assist 
students (and teachers and researchers) working with data. 

We do not guarantee that we will be able to solve your problems, but we will 
do our best to help you.

Our [website](https://kub.kb.dk/datalab)

Our mail: kubdatalab@kb.dk



:::: keypoints:
   - "Practice is important!"
   - "Working on data that YOU find interesting is a really good idea,"
   - "The amount of ressources online is immense."
   - "KUB Datalab is there for your."
   
::::

